import type { Grant } from "./types";

export const GRANTS_DB: Grant[] = [
  {
    id: "g1",
    title: "Small Business Growth Grants Program WA",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/small-business-growth-grants-program-wa",
    amount_min: 2000,
    amount_max: 10000,
    amount_text: "$2,000–$10,000",
    states: ["WA"],
    industries: ["General"],
    sizes: ["Small", "Startup"],
    status: "open",
    close_date: "Ongoing",
    description: "Matched funding to help eligible small business owners invest in expert advice and services to grow their business, build capability and strengthen long-term success.",
    eligibility: "Must be a WA-based small business with fewer than 20 FTE employees and turnover under $5M.",
    grant_type: "voucher",
    category: "state",
    url: "https://business.gov.au/grants-and-programs/small-business-growth-grants-program-wa",
  },
  {
    id: "g2",
    title: "Export Market Development Grant (EMDG)",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/export-market-development-grants",
    amount_min: 5000,
    amount_max: 150000,
    amount_text: "$5,000–$150,000",
    states: ["National"],
    industries: ["Export", "Manufacturing", "Technology", "Agriculture", "Food & Beverage"],
    sizes: ["Small", "Medium"],
    status: "open",
    close_date: "Round-based",
    description: "Reimburses up to 50% of eligible export marketing and promotion expenses to help Australian businesses expand into international markets.",
    eligibility: "Australian business with income under $20M. Must have spent at least $15,000 on eligible export promotion activities.",
    grant_type: "grant",
    category: "export",
    url: "https://business.gov.au/grants-and-programs/export-market-development-grants",
  },
  {
    id: "g3",
    title: "R&D Tax Incentive",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/research-and-development-tax-incentive",
    amount_min: 0,
    amount_max: 0,
    amount_text: "Tax offset up to 43.5%",
    states: ["National"],
    industries: ["Technology", "Manufacturing", "Healthcare", "Agriculture", "Energy", "Research"],
    sizes: ["Small", "Medium", "Startup"],
    status: "open",
    close_date: "Ongoing (annual)",
    description: "Provides a tax offset to encourage Australian companies to invest in research and development activities that might not otherwise be undertaken.",
    eligibility: "Incorporated company conducting eligible R&D activities in Australia. Must register with AusIndustry within 10 months of income year end.",
    grant_type: "tax_incentive",
    category: "federal",
    url: "https://business.gov.au/grants-and-programs/research-and-development-tax-incentive",
  },
  {
    id: "g4",
    title: "Industry Growth Program",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/industry-growth-program",
    amount_min: 50000,
    amount_max: 5000000,
    amount_text: "$50,000–$5,000,000",
    states: ["National"],
    industries: ["Manufacturing", "Technology", "Healthcare", "Energy", "Defence", "Agriculture"],
    sizes: ["Small", "Medium", "Startup"],
    status: "open",
    close_date: "Apply anytime (advisory stage)",
    description: "Supports innovative SMEs to commercialise novel products, processes and services. Includes advisory services followed by co-funded grant for commercialisation projects.",
    eligibility: "Australian SME with innovative product/process in National Reconstruction Fund priority areas. Must complete advisory stage before grant application.",
    grant_type: "grant",
    category: "federal",
    url: "https://business.gov.au/grants-and-programs/industry-growth-program",
  },
  {
    id: "g5",
    title: "CSIRO Kick-Start",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/csiro-kickstart",
    amount_min: 10000,
    amount_max: 50000,
    amount_text: "$10,000–$50,000 (matched)",
    states: ["National"],
    industries: ["Technology", "Manufacturing", "Healthcare", "Agriculture", "Energy", "Research"],
    sizes: ["Small", "Startup"],
    status: "open",
    close_date: "Ongoing",
    description: "Matched funding for Australian startups and small SMEs to access CSIRO research expertise and capabilities to undertake R&D activities that will grow your business.",
    eligibility: "Australian startup or SME with fewer than 20 employees and annual turnover under $5M. Must have an eligible R&D project.",
    grant_type: "grant",
    category: "research",
    url: "https://business.gov.au/grants-and-programs/csiro-kickstart",
  },
  {
    id: "g6",
    title: "Innovation Connect (ICON) Grants ACT",
    source: "act.gov.au",
    source_url: "https://www.act.gov.au/business/apply-for-grants-and-funding",
    amount_min: 10000,
    amount_max: 30000,
    amount_text: "$10,000–$30,000 (matched)",
    states: ["ACT"],
    industries: ["Technology", "General"],
    sizes: ["Startup", "Small"],
    status: "open",
    close_date: "Ongoing",
    description: "Matched funding grants for early-stage entrepreneurs and start-ups in the ACT to kick-start their innovation journey.",
    eligibility: "ACT-based early-stage business or startup. Must demonstrate an innovative idea with commercial potential.",
    grant_type: "grant",
    category: "state",
    url: "https://www.act.gov.au/business/apply-for-grants-and-funding",
  },
  {
    id: "g7",
    title: "Business Growth Loan Scheme TAS",
    source: "business.tas.gov.au",
    source_url: "https://www.business.tas.gov.au/funding",
    amount_min: 50000,
    amount_max: 5000000,
    amount_text: "$50,000–$5,000,000",
    states: ["TAS"],
    industries: ["General"],
    sizes: ["Small", "Medium"],
    status: "open",
    close_date: "Ongoing",
    description: "Low-interest loans to assist Tasmanian businesses to develop, expand or undertake new projects that promote growth in the Tasmanian economy.",
    eligibility: "Tasmanian business that can demonstrate the project will create jobs and economic growth in Tasmania.",
    grant_type: "loan",
    category: "state",
    url: "https://www.business.tas.gov.au/funding",
  },
  {
    id: "g8",
    title: "Innovation Booster Grant WA",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/innovation-booster-grant-wa",
    amount_min: 5000,
    amount_max: 50000,
    amount_text: "Up to $50,000 (matched)",
    states: ["WA"],
    industries: ["Technology", "Manufacturing", "Research"],
    sizes: ["Startup", "Small"],
    status: "open",
    close_date: "Ongoing",
    description: "Funding for WA start-ups and small businesses to commercialise innovative ideas or projects, and to expand to create jobs.",
    eligibility: "WA-based startup or small business with an innovative product or service to commercialise. Reduced matched funding for underrepresented groups.",
    grant_type: "grant",
    category: "state",
    url: "https://business.gov.au/grants-and-programs/innovation-booster-grant-wa",
  },
  {
    id: "g9",
    title: "Future Made in Australia Innovation Fund",
    source: "arena.gov.au",
    source_url: "https://arena.gov.au/funding/future-made-in-australia-innovation-fund/",
    amount_min: 500000,
    amount_max: 50000000,
    amount_text: "Up to $1.5 billion total pool",
    states: ["National"],
    industries: ["Energy", "Manufacturing"],
    sizes: ["Medium", "Small"],
    status: "open",
    close_date: "Ongoing until exhausted",
    description: "ARENA-administered fund providing grants for pre-commercial innovation, demonstration and deployment of renewable energy and low emission technologies.",
    eligibility: "Australian entity with project in green metals, renewable energy technology manufacturing, or low carbon liquid fuels. TRL 4+ typically required.",
    grant_type: "grant",
    category: "energy",
    url: "https://arena.gov.au/funding/future-made-in-australia-innovation-fund/",
  },
  {
    id: "g10",
    title: "Regional Economic Development Grants WA",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs/regional-economic-development-grants-wa",
    amount_min: 25000,
    amount_max: 250000,
    amount_text: "$25,000–$250,000",
    states: ["WA"],
    industries: ["General", "Agriculture", "Tourism", "Manufacturing"],
    sizes: ["Small", "Medium"],
    status: "open",
    close_date: "Round-based",
    description: "Funding for businesses undertaking projects in regional Western Australia that contribute to economic growth in local communities.",
    eligibility: "Must be a legal entity operating in regional WA. Minimum 50% cash co-contribution required.",
    grant_type: "grant",
    category: "state",
    url: "https://business.gov.au/grants-and-programs/regional-economic-development-grants-wa",
  },
  {
    id: "g11",
    title: "Instant Asset Write-Off",
    source: "ato.gov.au",
    source_url: "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/depreciation-and-capital-expenses-and-allowances/simpler-depreciation-for-small-business",
    amount_min: 0,
    amount_max: 20000,
    amount_text: "Up to $20,000 per asset",
    states: ["National"],
    industries: ["General"],
    sizes: ["Small", "Startup", "Sole Trader"],
    status: "open",
    close_date: "30 June 2025 (may extend)",
    description: "Allows small businesses to immediately deduct the cost of eligible assets costing less than $20,000 each, rather than depreciating over time.",
    eligibility: "Small business with aggregated annual turnover under $10M. Asset must be first used or installed ready for use in the relevant income year.",
    grant_type: "tax_incentive",
    category: "federal",
    url: "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/depreciation-and-capital-expenses-and-allowances/simpler-depreciation-for-small-business",
  },
  {
    id: "g12",
    title: "Advance Queensland Industry Research Fellowships",
    source: "business.qld.gov.au",
    source_url: "https://www.business.qld.gov.au/running-business/growing-business/becoming-innovative/grants",
    amount_min: 50000,
    amount_max: 200000,
    amount_text: "Up to $200,000",
    states: ["QLD"],
    industries: ["Technology", "Research", "Healthcare", "Manufacturing", "Energy"],
    sizes: ["Small", "Medium", "Startup"],
    status: "open",
    close_date: "Round-based",
    description: "Supports collaborative research between Queensland businesses and universities to drive innovation and solve industry challenges.",
    eligibility: "Queensland-based business partnering with a QLD university. Project must address an industry challenge with commercial potential.",
    grant_type: "grant",
    category: "innovation",
    url: "https://www.business.qld.gov.au/running-business/growing-business/becoming-innovative/grants",
  },
  {
    id: "g13",
    title: "SA Small Business Strategy Grant",
    source: "sa.gov.au",
    source_url: "https://www.sa.gov.au/topics/business-and-trade/business-grants",
    amount_min: 1000,
    amount_max: 5000,
    amount_text: "$1,000–$5,000",
    states: ["SA"],
    industries: ["General"],
    sizes: ["Small", "Startup", "Sole Trader"],
    status: "open",
    close_date: "Ongoing",
    description: "Helps South Australian small businesses access professional business advice and strategic planning support to strengthen their operations.",
    eligibility: "SA-based small business. Must use funding for professional advisory services from an approved provider.",
    grant_type: "grant",
    category: "state",
    url: "https://www.sa.gov.au/topics/business-and-trade/business-grants",
  },
  {
    id: "g14",
    title: "Defence Industry Development Grant",
    source: "business.gov.au",
    source_url: "https://business.gov.au/grants-and-programs",
    amount_min: 10000,
    amount_max: 50000,
    amount_text: "$10,000–$50,000",
    states: ["National"],
    industries: ["Defence", "Manufacturing", "Technology"],
    sizes: ["Small", "Medium"],
    status: "open",
    close_date: "Ongoing",
    description: "Supports small and medium Australian businesses operating in the defence sector to enhance their capabilities, capacity and security posture.",
    eligibility: "Australian SME operating in or seeking to enter the defence supply chain. Must demonstrate how grant will enhance defence capability.",
    grant_type: "grant",
    category: "federal",
    url: "https://business.gov.au/grants-and-programs",
  },
  {
    id: "g15",
    title: "NSW Small Business Fees and Charges Rebate",
    source: "nsw.gov.au",
    source_url: "https://www.nsw.gov.au/grants-and-funding",
    amount_min: 500,
    amount_max: 2000,
    amount_text: "Up to $2,000",
    states: ["NSW"],
    industries: ["General"],
    sizes: ["Small", "Startup", "Sole Trader"],
    status: "open",
    close_date: "Until funds exhausted",
    description: "Rebate for eligible NSW small businesses to offset the cost of NSW and local government fees and charges.",
    eligibility: "NSW small business with total Australian wages below the payroll tax threshold. Must have an ABN and NSW business address.",
    grant_type: "rebate",
    category: "state",
    url: "https://www.nsw.gov.au/grants-and-funding",
  },
  {
    id: "g16",
    title: "Business Victoria Energy Efficiency Grants",
    source: "business.vic.gov.au",
    source_url: "https://business.vic.gov.au/grants-and-programs",
    amount_min: 5000,
    amount_max: 20000,
    amount_text: "$5,000–$20,000",
    states: ["VIC"],
    industries: ["General", "Manufacturing", "Retail", "Tourism"],
    sizes: ["Small", "Medium"],
    status: "open",
    close_date: "Round-based",
    description: "Helps Victorian businesses invest in energy-efficient equipment and processes to reduce energy costs and improve sustainability.",
    eligibility: "Victorian business with an ABN. Must demonstrate how funding will reduce energy consumption. Co-contribution may be required.",
    grant_type: "grant",
    category: "state",
    url: "https://business.vic.gov.au/grants-and-programs",
  },
];

export const QUIZ_STEPS = [
  {
    id: "state" as const,
    title: "Where is your business based?",
    type: "single" as const,
    options: [
      { value: "NSW", label: "New South Wales" },
      { value: "VIC", label: "Victoria" },
      { value: "QLD", label: "Queensland" },
      { value: "SA", label: "South Australia" },
      { value: "WA", label: "Western Australia" },
      { value: "TAS", label: "Tasmania" },
      { value: "NT", label: "Northern Territory" },
      { value: "ACT", label: "ACT" },
    ],
  },
  {
    id: "industries" as const,
    title: "What industry are you in?",
    subtitle: "Select all that apply",
    type: "multi" as const,
    options: [
      { value: "Construction", label: "Construction & Trades" },
      { value: "Technology", label: "Technology & Digital" },
      { value: "Manufacturing", label: "Manufacturing" },
      { value: "Retail", label: "Retail & E-commerce" },
      { value: "Agriculture", label: "Agriculture & Food" },
      { value: "Healthcare", label: "Healthcare" },
      { value: "Tourism", label: "Tourism & Hospitality" },
      { value: "Energy", label: "Energy & Environment" },
      { value: "Defence", label: "Defence & Aerospace" },
      { value: "Export", label: "Import/Export" },
      { value: "Research", label: "Research & Innovation" },
      { value: "Mining", label: "Mining & Resources" },
      { value: "Arts", label: "Arts & Creative Industries" },
      { value: "General", label: "Other / General" },
    ],
  },
  {
    id: "sizes" as const,
    title: "How big is your business?",
    type: "single" as const,
    options: [
      { value: "Sole Trader", label: "Just me (Sole Trader)" },
      { value: "Startup", label: "Startup (pre-revenue or early stage)" },
      { value: "Small", label: "Small (1–19 employees)" },
      { value: "Medium", label: "Medium (20–199 employees)" },
      { value: "Non-profit", label: "Non-profit / Social Enterprise" },
    ],
  },
  {
    id: "revenue" as const,
    title: "What\u2019s your annual revenue?",
    type: "single" as const,
    options: [
      { value: "pre_revenue", label: "Pre-revenue / Just starting" },
      { value: "under_500k", label: "Under $500K" },
      { value: "500k_2m", label: "$500K \u2013 $2M" },
      { value: "2m_10m", label: "$2M \u2013 $10M" },
      { value: "over_10m", label: "$10M+" },
    ],
  },
  {
    id: "purposes" as const,
    title: "What do you need funding for?",
    subtitle: "Select all that apply",
    type: "multi" as const,
    options: [
      { value: "grow", label: "Grow my business" },
      { value: "export", label: "Export to new markets" },
      { value: "innovate", label: "R&D / Innovation" },
      { value: "hire", label: "Hire staff" },
      { value: "equipment", label: "Equipment / Assets" },
      { value: "digital", label: "Go digital" },
      { value: "energy", label: "Energy efficiency" },
      { value: "training", label: "Training & upskilling" },
    ],
  },
  {
    id: "activities" as const,
    title: "Does your business do any of these?",
    subtitle: "Helps us find specialist grants — select all that apply",
    type: "multi" as const,
    options: [
      { value: "apprentices", label: "Hire apprentices or trainees" },
      { value: "export", label: "Export products or services overseas" },
      { value: "research", label: "R&D or develop new products / processes" },
      { value: "energy_intensive", label: "High energy use (manufacturing, processing)" },
      { value: "regional", label: "Based in a regional or rural area" },
      { value: "social_enterprise", label: "Social enterprise or not-for-profit" },
      { value: "none", label: "None of the above" },
    ],
  },
];
